In [1]:
from __future__ import print_function
import torch

In [2]:
# 초기화되지 않은 5x3 행렬 생성
# 초기화되지 않은 행령이 생성되면 그 시점에 할당 된 메모리에 존재하던 값들이 초기값으로 나타남  
x = torch.empty(5, 3)
print(x)

tensor([[1.5414e-20, 9.2486e-43, 1.5408e-20],
        [9.2486e-43, 1.5415e-20, 9.2486e-43],
        [1.5415e-20, 9.2486e-43, 1.5408e-20],
        [9.2486e-43, 1.5408e-20, 9.2486e-43],
        [1.5408e-20, 9.2486e-43, 1.5408e-20]])


In [3]:
# 무작위로 초기화 된 행렬
x = torch.rand(5, 3)
print(x)

tensor([[0.4032, 0.6887, 0.7603],
        [0.8735, 0.4901, 0.5736],
        [0.5735, 0.9929, 0.1719],
        [0.8787, 0.6925, 0.3965],
        [0.7212, 0.6738, 0.2023]])


In [4]:
# type이 long이고 0으로 채워진 행렬 생성
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
# 데이터로부터 tensor를 직접 생성
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
# 기존 tensor를 바탕으로 새로운 tensor를 생성
# 이들 메소드(method)는 사용자로부터 새로운 값을 제공받지 않으면 입력 tensor의 속성돌(ex.dtype) 재사용
x = x.new_ones(5, 3, dtype=torch.double)     # new_* 메소드는 크기를 받음
print(x)

x = torch.rand_like(x, dtype=torch.float)    # dtype을 오버라이드(Override) 
print(x)                                     # 결과는 동일한 크기를 가짐

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.7238, 0.3080, 0.5078],
        [0.7136, 0.4991, 0.8521],
        [0.2653, 0.9055, 0.0144],
        [0.0148, 0.9083, 0.0334],
        [0.5312, 0.2139, 0.7577]])


In [7]:
# 행렬의 크기를 구함
print(x.size())

torch.Size([5, 3])


In [8]:
# 덧셈 문법 1
y = torch.rand(5, 3)
print(x + y)

tensor([[1.0959, 1.1878, 1.1214],
        [1.6159, 0.8811, 1.6966],
        [0.8122, 1.5858, 0.6287],
        [0.7080, 1.3360, 0.9920],
        [0.9402, 1.1328, 0.8275]])


In [9]:
# 덧셈 문법 2
print(torch.add(x, y))

tensor([[1.0959, 1.1878, 1.1214],
        [1.6159, 0.8811, 1.6966],
        [0.8122, 1.5858, 0.6287],
        [0.7080, 1.3360, 0.9920],
        [0.9402, 1.1328, 0.8275]])


In [10]:
# 덧셈 문법 3, 결과 tensor를 인자로 제공
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.0959, 1.1878, 1.1214],
        [1.6159, 0.8811, 1.6966],
        [0.8122, 1.5858, 0.6287],
        [0.7080, 1.3360, 0.9920],
        [0.9402, 1.1328, 0.8275]])


In [11]:
# 덧셈 문법 4, In-place 방식
# In-place 방식으로 tensor의 값을 변경하는 연산 뒤에는 _가 붙음. (ex. x.copy_(y))
y.add_(x)
print(y)

tensor([[1.0959, 1.1878, 1.1214],
        [1.6159, 0.8811, 1.6966],
        [0.8122, 1.5858, 0.6287],
        [0.7080, 1.3360, 0.9920],
        [0.9402, 1.1328, 0.8275]])


In [12]:
# 크기변경
x = torch.randn(4, 4)
y = x.view(16)
z= x.view(-1, 8)    # -1은 다른 차원을 보고 유추
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [13]:
# 만약 tensor에 값이 하나만 존재한다면, .item()을 통해 숫자 값을 얻을 수 있음
x = torch.rand(1)
print(x)
print(x.item())

tensor([0.5821])
0.5820731520652771


In [14]:
# torch tensor를 numpy 배열로 변환하기
a = torch.ones(5)
print(a)

b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [15]:
# tensor를 변경하면 numpy 배열의 값도 자동으로 변경
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [16]:
import numpy  as np

# numpy 배열을 torch tensor로 변환하기
# numpy 배열을 변경하면 tensor의 값도 자동으로 변경
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [17]:
# CUDA가 사용가능 한 환경에서만 실행 가능
# 'torch.device'를 사용하여 tensor를 GPU 안팎으로 이동
if torch.cuda.is_available():
    device = torch.device("cuda")            # CUDA 장치 객체(device object)로
    y = torch.ones_like(x, device=device)    # GPU 상에 직접적으로 tensor를 생성하거나
    x = x.to(device)                         # .to(cuda)를 사용하면 됨
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))         # .to는 dtype도 함께 변경 가능